[package]
name = "mz-controller-types"
description = "Shared types for the `mz-controller` crate"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
mz-cluster-client = { path = "../cluster-client" }
mz-compute-client = { path = "../compute-client" }
workspace-hack = { version = "0.0.0", path = "../workspace-hack" }

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]
